In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as pl

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.preprocessing import StandardScaler

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [4]:
df = pd.read_csv('../Data/Kaggle Dataset/fake_news.csv')

In [5]:
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [6]:
len(df['text'][0])

7518

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6335 entries, 0 to 6334
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  6335 non-null   int64 
 1   title       6335 non-null   object
 2   text        6335 non-null   object
 3   label       6335 non-null   object
dtypes: int64(1), object(3)
memory usage: 198.1+ KB


In [8]:
X = df.drop('label', axis=1)
X['content'] = X['title'] + X['text']
X.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text  \
0  Daniel Greenfield, a Shillman Journalism Fello...   
1  Google Pinterest Digg Linkedin Reddit Stumbleu...   
2  U.S. Secretary of State John F. Kerry said Mon...   
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...   
4  It's primary day in New York and front-runners...   

                                             content  
0  You Can Smell Hillary’s FearDaniel Greenfield,...  
1  Watch The Exact Moment Paul Ryan Committed Pol...  
2  Kerry to go to Paris in gesture of sympathyU.S...  
3  Bernie supporters on Twitter erupt in anger ag...  
4  The Battle of New York: Why This Primary Matte...

In [9]:
y = df['label'].apply(lambda x: 1 if x=='FAKE' else 0)
y.head()

0    1
1    1
2    0
3    1
4    0
Name: label, dtype: int64

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X['content'], y, test_size=0.2, random_state=101)

In [11]:
# Let us now try to use count vectorizer as a feature extraction method to do the classification

In [12]:
vect= CountVectorizer(stop_words='english',max_features=100)
x_train_count = vect.fit_transform(X_train)
x_test_count = vect.fit_transform(X_test)

In [13]:
tfidf_vect = TfidfVectorizer(stop_words='english',max_features=10000)
x_train_tf = tfidf_vect.fit_transform(X_train)
x_test_tf = tfidf_vect.fit_transform(X_test)

In [14]:
import scipy.sparse as sp
train_data = sp.hstack((x_train_count,x_train_tf))
test_data = sp.hstack((x_test_count,x_test_tf))

In [15]:
# Let us apply now different classification algorithms

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
# from sklearn.naive_bayes import GaussianNB
from sklearn.pipeline import Pipeline
from datetime import datetime

In [16]:
models = {'Logistic Regression':LogisticRegression(), 
         'Support Vector Classifier':SVC(),'Decision Tree':DecisionTreeClassifier(),
         'Random Forest':RandomForestClassifier(),'Neural Network':MLPClassifier(),
         'Stochastic Gradient Descent':SGDClassifier(), 'KNN':KNeighborsClassifier()}

for model, algorithm in models.items():
    start_time = datetime.now() 
    pipe = Pipeline([('model', algorithm)])
    pipe.fit(train_data ,y_train)
    end_time = datetime.now() 
    prediction = pipe.predict(test_data)
    print("\n \n ======= For {} ============".format(model))
    print('Accuracy Score : {} '.format(accuracy_score(prediction,y_test)))
    print('Confusion Matrix \n\n  ',confusion_matrix(prediction,y_test))
    print('\n Classification Report \n ')
    print(classification_report(prediction,y_test))
    time_difference = (end_time - start_time).total_seconds() * 10**3
    print("Execution time of program is: ", time_difference, "ms")

C:\Users\ArnabBiswas\anaconda3\envs\mlenv\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


======= For Logistic Regression ============
Accuracy Score : 0.6140489344909235 
Confusion Matrix 

   [[198  34]
 [455 580]]

 Classification Report 
 
              precision    recall  f1-score   support

           0       0.30      0.85      0.45       232
           1       0.94      0.56      0.70      1035

    accuracy                           0.61      1267
   macro avg       0.62      0.71      0.58      1267
weighted avg       0.83      0.61      0.66      1267

Execution time of program is:  669.866 ms
======= For Support Vector Classifier ============
Accuracy Score : 0.6827150749802684 
Confusion Matrix 

   [[321  70]
 [332 544]]

 Classification Report 
 
              precision    recall  f1-score   support

           0       0.49      0.82      0.61       391
           1       0.89      0.62      0.73       876

    accuracy                           0.68      1267
   macro avg       0.69      0.72      0.67      1267
weighted avg       0.76      0.68      0.69  

TypeError: A sparse matrix was passed, but dense data is required. Use X.toarray() to convert to a dense numpy array.

In [17]:
knn = KNeighborsClassifier()

In [18]:
knn.fit(train_data ,y_train)

KNeighborsClassifier()

In [19]:
prediction = knn.predict(test_data)

In [21]:
gnb = GaussianNB()
gnb.fit(train_data ,y_train)

TypeError: A sparse matrix was passed, but dense data is required. Use X.toarray() to convert to a dense numpy array.

In [22]:
print('Accuracy Score : {} '.format(accuracy_score(prediction,y_test)))
print('Confusion Matrix \n\n  ',confusion_matrix(prediction,y_test))
print('\n Classification Report \n ')
print(classification_report(prediction,y_test))

Accuracy Score : 0.5927387529597474 
Confusion Matrix 

   [[218  81]
 [435 533]]

 Classification Report 
 
              precision    recall  f1-score   support

           0       0.33      0.73      0.46       299
           1       0.87      0.55      0.67       968

    accuracy                           0.59      1267
   macro avg       0.60      0.64      0.57      1267
weighted avg       0.74      0.59      0.62      1267



In [14]:
x_train_count.shape

(5068, 100)

In [16]:
x_train_count

<1x100 sparse matrix of type '<class 'numpy.int64'>'
	with 28 stored elements in Compressed Sparse Row format>

In [22]:
len(vect.vocabulary_)

100

In [23]:
len(tfidf_vect.vocabulary_)

10000

In [24]:
vect.vocabulary_

{'democrats': 23,
 'does': 26,
 'cruz': 19,
 'people': 58,
 'week': 93,
 'right': 68,
 'republican': 66,
 'make': 48,
 'told': 83,
 'state': 76,
 'political': 62,
 'world': 97,
 'law': 45,
 'like': 46,
 'support': 78,
 'trump': 84,
 'new': 54,
 'said': 70,
 'way': 92,
 've': 86,
 'years': 99,
 'just': 43,
 'donald': 28,
 'say': 72,
 'know': 44,
 'bush': 7,
 'president': 63,
 'called': 8,
 'come': 15,
 'country': 17,
 'think': 79,
 'hillary': 39,
 'clinton': 14,
 'want': 89,
 'washington': 91,
 'government': 37,
 'day': 20,
 '2016': 1,
 'military': 50,
 'far': 30,
 'war': 90,
 'russia': 69,
 '000': 0,
 'times': 81,
 'americans': 6,
 'need': 53,
 'year': 98,
 'time': 80,
 'million': 51,
 'security': 74,
 'united': 85,
 'states': 77,
 'foreign': 33,
 'don': 27,
 'including': 41,
 'election': 29,
 'vote': 87,
 'win': 95,
 'republicans': 67,
 'gop': 36,
 'national': 52,
 'policy': 61,
 'obama': 56,
 'long': 47,
 'america': 4,
 'american': 5,
 'house': 40,
 'debate': 21,
 'today': 82,
 'vote

In [26]:
x_train_count.data

array([3, 1, 1, ..., 1, 1, 1], dtype=int64)